<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b3325394-3132-4c8a-a66c-e12bd866ef93</testSuiteGuid>
   <testCaseLink>
      <guid>15140fbc-0a06-4dd5-ad2f-1cd766cbc88d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC1</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9012f690-3a0a-487a-ab02-4dc849b5715f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>678408fa-e520-4bb2-ac9b-f4f830abc1d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b15a0445-4e7e-4ca4-9264-cd1afc48db9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6d7602e-20c3-43f2-b65c-1d37c044c8cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a89342d-d647-4b2f-b030-b16706340f95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>316fa4e1-8252-4ad7-8254-8807101dd49a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6aee524f-8fd3-4ae1-9e5a-9164af35af2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Account/TC4</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
